const routeRoutes = {
  home: "/",
  login: "/login",
  register: "/register",
  course: "/course/:id",

  courses: "/courses",
  curriculum: "/course/:id/:section?/:lecture?",
  loginSocial: "/social-login",
  resetPassword: "/reset-password",
  projects: "/projects",
  project: "/projects/:id",
  myTasks: "/my-tasks",
  notifications: "/notifications",
  myCourses: "/my-courses",
  flashcards: "/flashcards",
  followingMads: "/following-mads",
  funZone: "/fun-zone",
  myAchievements: "/my-achievements",
  myPoints: "/my-points",
  forum: "/forum",
  myProfile: "/my-profile",
  cart: "/cart",
  article: "/article/:id",
  forumCategory: "/forum/:id",
  forumTopic: "/forum/:id/:id",
  careerPlanner: "/career-planner",
  career: "/career-planner/:id",
  search: "/search",
  blog: "/blog",
  storybook: "/storybook",
  iframe: "/iframe",
};

export default routeRoutes;
