const routeRoutes = {
  home: "/",
  login: "/login",
  register: "/register",
  course: "/course/:id",
  authentication: "/authentication",
  courses: "/courses",
  curriculum: "/course/:id/:section?/:lecture?",
  page: "/page/:slug",
  myProfile: "/user/my-profile",
  myOrders: "/user/my-orders",
  myPayments: "/user/my-payments",
  myCourses: "/user/my-courses",
  // loginSocial: "/social-login",
  // resetPassword: "/reset-password",
  // projects: "/projects",
  // project: "/projects/:id",
  // myTasks: "/my-tasks",
  // notifications: "/notifications",
  // myCourses: "/my-courses",
  // flashcards: "/flashcards",
  // followingMads: "/following-mads",
  // funZone: "/fun-zone",
  // myAchievements: "/my-achievements",
  // myPoints: "/my-points",
  // forum: "/forum",
  // myProfile: "/my-profile",
  // cart: "/cart",
  // article: "/article/:id",
  // forumCategory: "/forum/:id",
  // forumTopic: "/forum/:id/:id",
  // careerPlanner: "/career-planner",
  // career: "/career-planner/:id",
  // search: "/search",
  // blog: "/blog",
  // storybook: "/storybook",
  // iframe: "/iframe",
};

export default routeRoutes;
